import type { Metadata } from "next";
import { ProgressProvider } from "./context/ProgressContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Echelon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 text-gray-800 font-sans antialiased`}
      >
       <ProgressProvider>{children}</ProgressProvider> 
      </body>
    </html>
  );
}
